[theme]
base = "dark"

primaryColor = "#6366F1"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#161B22"
textColor = "#E6EDF3"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false